[database]
host = "127.0.0.1"
username = "postgres"
password = "666666"
dbname = "trendy"

[task]
per_page = 10
authorization = "Bearer 118751|JS90aGpbQ13KTCIwYDWsCmZzd9YEwBJEwlpSbkXI" # deprecated

[login]
username = '********.1991@gmail.com'
password = '*********'

[other]
proxy_txt = "proxy-list.txt"
debug_mode = true  # If debug mode is enabled, the spider will only crawl one page and the data will be printed to the command line instead of being stored in the database.
