[database]
host = "127.0.0.1"
username = "root"
password = "123456"
dbname = "videos"

[task]
per_page = 10
authorization = "Bearer 109826|Nq0KELRMwg7HPR9T2PPnYzVuSw2ZfzEwsah475OT"

[other]
proxy_txt = "proxy-list.txt"
debug_mode = true  # If debug mode is enabled, the spider will only crawl one page and the data will be printed to the command line instead of being stored in the database.